#Assignment 1

Try Linear Regression just using numpy (Without Tensorflow/Pytorch or other torch library). You can optionally use sklearn (if you want)

In [207]:
# Import Numpy & PyTorch
import numpy as np
import torch

In [208]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
[91, 88, 64],
[87, 134, 58],
[102, 43, 37],
[69, 96, 70]], dtype='float32')

# Target (apples)
targets = np.array([[56],
[81],
[119],
[22],
[103]], dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [209]:
# Weights and biases
w = torch.randn(1, 3, requires_grad=True)
b = torch.randn(1, requires_grad=True)
print(w)
print(b)

tensor([[4.5220e-01, 1.0669e+00, 8.9831e-04]], requires_grad=True)
tensor([-0.3799], requires_grad=True)


In [210]:
def model(x):
    return torch.mm(x, w.t(), out=None) +b

In [211]:
# Generate predictions
preds = model(inputs)
print("Prediction : ",preds)
print("Targets :",targets)

Prediction :  tensor([[104.1523],
        [134.7159],
        [181.9797],
        [ 91.6547],
        [133.3082]], grad_fn=<AddBackward0>)
Targets : tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [212]:
#MSE loss function
# import torch.nn as nn
def mse(P,T):
  diff = 0
  i=0
  sum=0
  n = len(T)
  for k in range(0,n) :
    i += 1
    diff = T[k] - P[k]
    square = diff * diff
    sum += square
  mean =  sum / i
  return mean
  
output = mse(preds, targets)
print("Loss : ",output)


Loss :  tensor([2988.1667], grad_fn=<DivBackward0>)


In [213]:
# Compute gradients
print("gradients : ",output.backward())

gradients :  None


In [214]:
# Gradients for weights
print(w)
print(w.grad)

tensor([[4.5220e-01, 1.0669e+00, 8.9831e-04]], requires_grad=True)
tensor([[9231.4121, 8918.8838, 5543.9917]])


In [215]:
# Gradients for biases
print(b)
print(b.grad)

tensor([-0.3799], requires_grad=True)
tensor([105.9243])


In [216]:
# Adjust weights & reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

print(w)
print(b)

tensor([[ 0.3599,  0.9777, -0.0545]], requires_grad=True)
tensor([-0.3810], requires_grad=True)


In [217]:
new_preds = model(inputs)
new_loss = mse(new_preds, targets)

print("New Loss : ",new_loss)

New Loss :  tensor([1382.3075], grad_fn=<DivBackward0>)


In [218]:
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [219]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor([66.1164], grad_fn=<DivBackward0>)


#Assignment 2

Using Inbuilt Functions

Try Linear regression on same prediction data using Tensorflow

In [220]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
[91, 88, 64],
[87, 134, 58],
[102, 43, 37],
[69, 96, 70]], dtype='float32')

# Target (apples)
targets = np.array([[56],
[81],
[119],
[22],
[103]], dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [221]:
# Weights and biases
w = torch.randn(1, 3, requires_grad=True)
b = torch.randn(1, requires_grad=True)
print(w)
print(b)

tensor([[-1.6424, -0.8742,  0.1506]], requires_grad=True)
tensor([-2.6842], requires_grad=True)


In [222]:
def model(x):
    return x @ w.t() + b

In [223]:
# Generate predictions
preds = model(inputs)
print("Prediction : ",preds)
print("Targets :",targets)

Prediction :  tensor([[-174.6746],
        [-219.4333],
        [-253.9794],
        [-202.2276],
        [-189.3903]], grad_fn=<AddBackward0>)
Targets : tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [224]:
import torch.nn as nn
loss = nn.MSELoss()
output = loss(preds, targets)
output.backward()
print("Loss :",output)

Loss : tensor(83670.9375, grad_fn=<MseLossBackward0>)


In [225]:
# Gradients for weights
print(w)
print(w.grad)
# Gradients for biases
print(b)
print(b.grad)

tensor([[-1.6424, -0.8742,  0.1506]], requires_grad=True)
tensor([[-47869.6172, -51833.5312, -31817.3145]])
tensor([-2.6842], requires_grad=True)
tensor([-568.2821])


In [226]:
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [228]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor([12.8490], grad_fn=<DivBackward0>)
