# Naive Bayes classifier

In [135]:
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB, MultinomialNB

In [136]:
weather = ['Sunny', 'Sunny', 'Overcast', 'Rainy', 'Rainy','Rainy', 'Overcast',
'Sunny', 'Sunny', 'Rainy', 'Sunny', 'Overcast', 'Overcast', 'Rainy']

temp = ['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild',
'Cool','Mild','Mild','Mild','Hot','Mild']

play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes',
'Yes','Yes','Yes','Yes','No']

In [137]:
#creating labelEncoder
le = preprocessing.LabelEncoder()
# Converting string labels into numbers.
weather_encoded=le.fit_transform(weather)
print("Weather:" ,weather_encoded)

Weather: [2 2 0 1 1 1 0 2 2 1 2 0 0 1]


In [138]:
temp_encoded=le.fit_transform(temp)
label=le.fit_transform(play)
print("Temp:",temp_encoded)
print("Play:",label)

Temp: [1 1 1 2 0 0 0 2 0 2 2 2 1 2]
Play: [0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [139]:
#Combinig weather and temp into single listof tuples
features=tuple(zip(weather_encoded,temp_encoded))
print("Features:",features)

Features: ((2, 1), (2, 1), (0, 1), (1, 2), (1, 0), (1, 0), (0, 0), (2, 2), (2, 0), (1, 2), (2, 2), (0, 2), (0, 1), (1, 2))


In [140]:
#Create a Classifier
model=MultinomialNB()
# Train the model using the training sets
model.fit(features,label)

MultinomialNB()

In [141]:
#Predict Output
predicted= model.predict([[0,2]]) # 0:Overcast, 2:Mild
print("Predicted Value:", predicted)

Predicted Value: [1]


In [142]:
predicted= model.predict([[2,2]]) # 2:Sunny, 2:Mild
print("Predicted Value:", predicted)

Predicted Value: [1]


#Exercise:

Manually answer is 

1) p(play = "yes" / weather = "Rainy" , Temp = "Mild")

==> play = yes : 0.624


==> play = no : 0.374 

In [143]:
predicted= model.predict([[1,2]]) # 2:Rainy, 2:Mild
print("Predicted Value:", predicted)

Predicted Value: [1]


Will you play if the temperature is ‘Hot’ and weather is ‘overcast’?

In [144]:
predicted= model.predict([[0,1]]) # 2:Overcast, 2:Hot
print("Predicted Value:", predicted)

Predicted Value: [1]


1) find probability of examples in given below

2) class prior and likelihood 

3) smoothing 

#Exercise2:

In [145]:
#Import scikit-learn dataset library
import numpy as np
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
#Load dataset
iris = datasets.load_iris()

In [146]:
# print the names of the 13 features
print("Features: ", iris.feature_names)
# print the label type of wine(class_0, class_1, class_2)
print("Labels: ", iris.target_names)
# print data(feature)shape
print("\nData shape: ",iris.data.shape)
#print data(target)shape
print("\nTraget shape: ",iris.target.shape)
#print("\nData: ",iris.data)
#print("\nTarget: ",iris.target)
print("\nData type: ",type(iris.data))
newdata = iris.data[50:,:]
newtarget = iris.target[50:]
# print data(feature)shape
print("\nNew Data shape: ",newdata.shape)
#print data(target)shape
print("\nNew Traget shape: ",newtarget.shape)

Features:  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Labels:  ['setosa' 'versicolor' 'virginica']

Data shape:  (150, 4)

Traget shape:  (150,)

Data type:  <class 'numpy.ndarray'>

New Data shape:  (100, 4)

New Traget shape:  (100,)


In [147]:
#import the necessary module
from sklearn.model_selection import train_test_split
#split data set into train and test sets
data_train, data_test, target_train, target_test = train_test_split(newdata,
newtarget, test_size = 0.30, random_state = 5)

In [148]:
import numpy as np
gnb = GaussianNB()
#Train the model using the training sets
gnb.fit(data_train, target_train)
#Predict the response for test dataset
target_pred = gnb.predict(data_test)

In [149]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 0.9


In [150]:
#Import confusion_matrix from scikit-learn metrics module for confusion_matrix
from sklearn.metrics import confusion_matrix
print("confusion matrix : \n")
confusion_matrix(target_test, target_pred)

confusion matrix : 



array([[16,  1],
       [ 2, 11]])

In [151]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred)
recall = recall_score(target_test, target_pred)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: 0.8888888888888888
recall: 0.9411764705882353


#Exercise3:

In [152]:
#import the necessary module
from sklearn.model_selection import train_test_split
#split data set into train and test sets
data_train, data_test, target_train, target_test = train_test_split(iris.data,
iris.target, test_size = 0.30, random_state = 10)

In [153]:
import numpy as np
gnb = GaussianNB()
#Train the model using the training sets
gnb.fit(data_train, target_train)
#Predict the response for test dataset
target_pred = gnb.predict(data_test)

In [154]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 1.0


In [155]:
#Import confusion_matrix from scikit-learn metrics module for confusion_matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

array([[14,  0,  0],
       [ 0, 17,  0],
       [ 0,  0, 14]])

In [156]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [1. 1. 1.]
recall: [1. 1. 1.]


#Assignment:


6) Task 1: Try the algo on Dataset3 -
LabelEncoding of features:and Train test Division 95%-5%

Task 2: Apply algorithm on breast cancer wisconsin dataset - One Hot Encoding of features: and Train test Division 50%-50%

In [157]:
#connection to drive
import pandas as pd
from google.colab import drive
from sklearn import datasets 
from sklearn import metrics 
from sklearn.linear_model import LogisticRegression 
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB, MultinomialNB

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [158]:
#fetch file
data=pd.read_csv('/content/drive/MyDrive/COLAB/Dataset3.csv')


In [159]:
le = preprocessing.LabelEncoder()

feature  = data.iloc[:,:-1] #find matrix from data set
target = data.iloc[:,-1].values

# Converting string labels into numbers.
outlook_encoded=le.fit_transform(feature["Outlook"])
Temp_encoded=le.fit_transform(feature["Temp"])
Wind_encoded=le.fit_transform(feature["Wind"])

feature= feature.drop(["Outlook","Temp","Wind"],axis=1)
feature["Outlook"] = outlook_encoded
feature["Temp"] = Temp_encoded
feature["Wind"] = Wind_encoded 
feature

Humidity  Outlook  Temp  Wind
0          1        1     1     0
1          2        1     1     1
2          1        0     1     0
3          1        1     2     0
4          1        2     0     0
5          0        0     0     1
6          1        0     0     1
7          1        1     2     0
8          0        0     0     0
9          2        2     2     0
10         2        1     0     1
11         0        0     2     1
12         1        0     1     0
13         1        2     2     1

###Test Size is very low that's why accuracy is low

In [160]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.metrics import accuracy_score

import time
#split data set into train and test sets
data_train, data_test, target_train, target_test = train_test_split(feature.values,
target, test_size = 0.05, random_state = 144)

In [161]:
import numpy as np
gnb = GaussianNB()
#Train the model using the training sets
gnb.fit(data_train, target_train)
#Predict the response for test dataset
target_pred = gnb.predict(data_test)


In [162]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 0.0


In [163]:
#Import confusion_matrix from scikit-learn metrics module for confusion_matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

array([[0, 0],
       [1, 0]])

In [164]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [0. 0.]
recall: [0. 0.]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [165]:
#What will be the value of Play, if Outlook is ’Rainy’, Temperature is ’Mild’, Humidity =’Normal’, and Wind = ’False’?

print("predicted Value : ",gnb.predict([[2,1,2,0]]))

#What will be the value of Play, if Outlook is ’Sunny’, Temeprature is ’Cool’, Humidity =’High’, and Wind = ’True’?
print("predicted Value : ",gnb.predict([[0,2,0,1]]))


predicted Value :  [0]
predicted Value :  [0]


##Now Increase Value of Test Size 

In [166]:
data_train, data_test, target_train, target_test = train_test_split(feature.values,
target, test_size = 0.44, random_state = 144)

#Train the model using the training sets
gnb.fit(data_train, target_train)
#Predict the response for test dataset
target_pred = gnb.predict(data_test)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

print("Confusion Matrix: \n",confusion_matrix(target_test, target_pred))

precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

#What will be the value of Play, if Outlook is ’Rainy’, Temperature is ’Mild’, Humidity =’Normal’, and Wind = ’False’?
print("predicted Value : ",gnb.predict([[2,1,2,0]]))
#What will be the value of Play, if Outlook is ’Sunny’, Temeprature is ’Cool’, Humidity =’High’, and Wind = ’True’?
print("predicted Value : ",gnb.predict([[0,2,0,1]]))

Accuracy: 0.7142857142857143
Confusion Matrix: 
 [[2 2]
 [0 3]]
precision: [1.  0.6]
recall: [0.5 1. ]
predicted Value :  [0]
predicted Value :  [1]


#2

Apply algorithm on breast cancer wisconsin dataset - One Hot Encoding of features: and
Train test Division 50%-50%

In [167]:
#fetch file
data=pd.read_csv('/content/drive/MyDrive/COLAB/data.csv')
data

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0      842302         M  ...                  0.11890          NaN
1      842517         M  ...                  0.08902          NaN
2    84300903         M  ...                  0.08758          NaN
3    84348301         M  ...                  0.17300          NaN
4    84358402         M  ...                  0.07678          NaN
..        ...       ...  ...                      ...          ...
564    926424         M  ...                  0.07115          NaN
565    926682         M  ...                  0.06637          NaN
566    926954         M  ...                  0.07820          NaN
567    927241         M  ...                  0.12400          NaN
568     92751         B  ...                  0.07039          NaN

[569 rows x 33 columns]

In [168]:
data.drop(data.columns[[-1, 0]], axis=1, inplace=True)

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   diagnosis                569 non-null    object 
 1   radius_mean              569 non-null    float64
 2   texture_mean             569 non-null    float64
 3   perimeter_mean           569 non-null    float64
 4   area_mean                569 non-null    float64
 5   smoothness_mean          569 non-null    float64
 6   compactness_mean         569 non-null    float64
 7   concavity_mean           569 non-null    float64
 8   concave points_mean      569 non-null    float64
 9   symmetry_mean            569 non-null    float64
 10  fractal_dimension_mean   569 non-null    float64
 11  radius_se                569 non-null    float64
 12  texture_se               569 non-null    float64
 13  perimeter_se             569 non-null    float64
 14  area_se                  5

In [169]:
features_mean= list(data.columns[1:11])
features_mean


['radius_mean',
 'texture_mean',
 'perimeter_mean',
 'area_mean',
 'smoothness_mean',
 'compactness_mean',
 'concavity_mean',
 'concave points_mean',
 'symmetry_mean',
 'fractal_dimension_mean']

In [170]:
diag_map = {'M':1, 'B':0}
data['diagnosis'] = data['diagnosis'].map(diag_map)
data

diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0            1        17.99  ...          0.4601                  0.11890
1            1        20.57  ...          0.2750                  0.08902
2            1        19.69  ...          0.3613                  0.08758
3            1        11.42  ...          0.6638                  0.17300
4            1        20.29  ...          0.2364                  0.07678
..         ...          ...  ...             ...                      ...
564          1        21.56  ...          0.2060                  0.07115
565          1        20.13  ...          0.2572                  0.06637
566          1        16.60  ...          0.2218                  0.07820
567          1        20.60  ...          0.4087                  0.12400
568          0         7.76  ...          0.2871                  0.07039

[569 rows x 31 columns]

In [171]:
X = data.loc[:,features_mean]
y = data.loc[:, 'diagnosis']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.5, random_state =144)


gnb = GaussianNB()
#Train the model using the training sets
gnb.fit(data_train, target_train)
#Predict the response for test dataset
target_pred = gnb.predict(data_test)
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 0.7142857142857143


In [172]:
confusion_matrix(target_test, target_pred)

array([[2, 2],
       [0, 3]])

In [173]:
precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [1.  0.6]
recall: [0.5 1. ]
